version: "3"
services:
    mysqldb:
      container_name: mysqldb
      image: mysql:5.7
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=netflix
      volumes:
         - ./mysql/data:/var/lib/mysql
         - ./src/main/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    subscription-app:
      image: netflix-subscription-image
      build:
        context: ./
        dockerfile: Dockerfile
      depends_on:
        - mysqldb
      ports:
        - 8087:8080
      volumes:
        - /data/spring-boot-app