version: '3'

services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'netflix'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - /mydata/mysql
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  subscription-app:
    image: netflix-subscription-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
# Names our volume
volumes:
  my-db:
